### ISSUE TITLE
Przewroparka nie działa na Windows

### ISSUE THREAD

**Issue by SynneK1337** [Szczepancio/Przewroparka#4]
Kurwo zajebana to nie działa debilu gupi Patusie schizolu co nie umie powiedzieć r patlyku

**Comment by Szczepancio** [comment]
Co ty tam mówisz tym swoim spedalonym głosem?  
Przewroparka działa jak powinna, prócz Windowsa (potrzebuje cygwina, i ma problemy z permisjami Xmriga). Na razie muszę przepisać kod sieciowy do Winsocketów i spróbować skompilować w Visualu i sprawdzić czy ten sam problem występuje.

**Comment by SynneK1337** [comment]
Ta na pewno patusie gupi ladnie to tak falszowac dokumenty?
